spring.application.name=cotizador

## POSTGRE
spring.datasource.url=jdbc:postgresql://localhost:5432/prismaDB
spring.datasource.username=postgres
spring.datasource.password=1234

# CREATE ONLY FOR THE FIRST APPLICATION RUN
spring.jpa.hibernate.ddl-auto=create

# THEN USE UPDATE
# spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true